defaults: &defaults
  docker:
    - image: nerveshub/docker-build:latest
  working_directory: ~/repo

remote_docker: &remote_docker
  setup_remote_docker:
    version: 17.09.0-ce

docker_env: &docker_env
  run:
    name: Set docker env
    command: |
      if [ -z "$CIRCLE_TAG" ]; then
      BRANCH=$(git rev-parse --abbrev-ref HEAD)
        SHA=$(git rev-parse --short HEAD)
        TAG=$(echo "v.$BRANCH.$SHA" | sed 's/\//_/g')
      else
        TAG=$CIRCLE_TAG
      fi
      echo "export DOCKER_TAG=$TAG" >> $BASH_ENV
      echo "export DOCKER_IMAGE=nerveshub/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV

docker_build_test: &docker_build_test
  run:
    name: Build docker image
    command: |
      docker build \
        -t $DOCKER_IMAGE:$DOCKER_TAG .

docker_build_release: &docker_build_release
  run:
    name: Build docker image
    command: |
      docker build \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -f rel/Dockerfile.build .

docker_run_test: &docker_run_test
  run: 
    name: Run the tests
    command: |
      docker run \
        $DOCKER_IMAGE:$DOCKER_TAG \
        mix test
        
docker_artifact: &docker_image_save
  run:
    name: Save docker image artifact
    command: |
      mkdir -p ~/artifacts
      docker image save \
        -o ~/artifacts/$CIRCLE_PROJECT_REPONAME.$DOCKER_TAG.tar \
        $DOCKER_IMAGE:$DOCKER_TAG

docker_push: &docker_push
  run: 
    name: Push docker image to dockerhub
    command: |
      docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      docker push \
        $DOCKER_IMAGE:$DOCKER_TAG

version: 2
jobs:
  build_test:
    <<: *defaults
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - <<: *remote_docker
      - <<: *docker_env
      - <<: *docker_build_test
      - <<: *docker_run_test
      - <<: *docker_image_save
      - store_artifacts:
          path: ~/artifacts
          destination: docker

  build_release:
    <<: *defaults
    environment:
      MIX_ENV: prod
    steps:
      - checkout
      - <<: *remote_docker
      - <<: *docker_env
      - <<: *docker_build_release
      - <<: *docker_image_save
      - store_artifacts:
          path: ~/artifacts
          destination: docker
      - <<: *docker_push

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test:
          context: org-global
          filters:
            tags:
              only: /.*/
      - build_release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
